### ISSUE TITLE
[FEAT] Remove unnecessary subshells

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#21]
**Is your feature request related to a problem? Please describe.**
Remove unnecessary calls to `awk`

**Describe the solution you'd like**

```
% col_n () {
    [[ -n $ZSH_VERSION ]] && setopt local_options sh_word_split
    local col=$1
    local IFS=$' \t'
    while read -r line; do
        set $line  # Spilt by IFS and set into $1, $2, ...
        printf "%s\n" "${@:$col:1}"
    done;
}
% echo "one two three" | col_n 2
two
```

**Comment by CodesOfRishi** [comment]
This maybe a nice optimization! Will be looking into it!

**Comment by CodesOfRishi** [comment]
Thinking of implementing something like this:-
```bash
__smartcd::col_n() {
	local OLD_IFS=${IFS}
	
	# IFS value:
	# >  ^I$
	# > $
	IFS=" 	
	"

	local col=$1
	local count=1

	local _line
	read -r _line

	local _opt
	if [[ ${SMARTCD_CURRENT_SHELL} = "bash" ]]; then
		for _opt in ${_line}; do
			if [[ ${count} -eq "${col}" ]]; then
				printf '%s\n' "${_opt}"
				break
			fi
			count=$(( count + 1))

		done
	elif [[ ${SMARTCD_CURRENT_SHELL} = "zsh" ]]; then
		for _opt in ${=_line}; do
			if [[ ${count} -eq "${col}" ]]; then
				printf '%s\n' "${_opt}"
				break
			fi
			count=$(( count + 1))

		done
	fi

	IFS=${OLD_IFS}
}
```

- Since I'm not dealing with multiple lines when it comes to extracting a particular column, there's no need for loop for `read`.
- Custom `IFS` configuration contains a space, a tab & a new-line character.
- In the case of Zsh, using `${=var}` instead of enabling an option explicitly (like `sh_word_split`) seems like a better approach.
